server:
  port: 8101
spring:
  application:
    name: springcloud_user_consumer_8101
  datasource:
    name: TestConnection  #数据库名
    url: jdbc:mysql://localhost:3306/seatselection?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8 #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver #数据库链接驱动